---
name: BYU Browser OAuth PKCE Grant
description: BYU PKCE grant implementation
resources:
  - src: dist/**
    dest: ./
entrypoints:
  pkce-grant.js: 'ES Module - PKCE grant client'
  pkce-grant.min.js: 'Minified - ES Module - PKCE grant client'
  pkce-grant.nomodule.js: 'Transpiled PKCE grant client'
  pkce-grant.nomodule.min.js: 'Minfied - Transpiled PKCE grant client'
docs: https://github.com/byuweb/byu-browser-oauth-pkce
